version: "3.8"

services:
  daprfrontend:
    image: daprfrontend-container:latest
    build:
      context: .
      dockerfile: DaprFrontEnd/Dockerfile
    ports:
      - "8090:8090"

  daprfrontend-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "daprfrontend",
        "-placement-host-address",
        "placement:50006",
        "-app-port",
        "8090",
      ]
    depends_on:
      - daprfrontend
    network_mode: "service:daprfrontend"

  daprbackend:
    image: daprbackend-container:latest
    build:
      context: .
      dockerfile: DaprBackEnd/Dockerfile
    ports:
      - "8070:8070"

  daprbackend-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "daprbackend",
        "-placement-host-address",
        "placement:50006",
        "-app-port",
        "8070",
      ]
    depends_on:
      - daprbackend
    network_mode: "service:daprbackend"

  daprdashboard-dapr:
    image: daprio/dashboard:latest
    networks:
      - dapr
    ports:
      - "8080:8080"


  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr
networks:
  dapr:
